env:
    rcloneconfig: "ENCRYPTED[6eca794cd99f3b0c800eeff8d079bcf514f711803ac503feb34569d50e0189ea4e453f5e5229e68eff63551c79cfeada]"
    
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "l3773"
       - git config --global user.email "l3773683@gmail.com"
       - cd /tmp
       - time aria2c https://drive.fourninesix.workers.dev/0:/ccache/ccache.tar.gz -x16 -s50
       - time tar xf ccache.tar.gz
       - rm -rf ccache.tar.gz
       - mkdir -p /tmp/rom
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u git://github.com/LineageOS/android.git -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone https://github.com/Redmi-MT6768/android_device_xiaomi_mt6768-common -b lineage-19.0 device/xiaomi/mt6768-common --depth=1
      - git clone https://github.com/Redmi-MT6768/android_device_xiaomi_merlinx -b lineage-19.0 device/xiaomi/merlinx --depth=1
      - git clone https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768 -b twelve kernel/xiaomi/mt6768 --depth=1
      - git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_merlinx -b twelve vendor/xiaomi/merlinx --depth=1
      - git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_mt6768-ims -b twelve vendor/xiaomi/mt6768-ims --depth=1

  Build_script:
      - ./final.sh

  Upload_script:
      - ./ziping.sh