env: 
    rclone_config: "ENCRYPTED[fb2a09ad0b21f52faf35d6861c34c40311f9a48ed369ae5dd82a2ccfeb8bd5b74bc3b0dbf4d0a8f34c8cb1b511c4b68a]"
    
task:
    name: abogoboga
    timeout_in: 120m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: inok2341/anu:latest
      cpu: 8 
      memory: 32G 
    download_ccache_background_script: 
     - ./mengdownload
    sync_script: 
      - ./sinkronisasi 
    build_uploads_script: 
      - ./membuat_akhir 
    mengunggah_script:
      - ./mengunggah