env:
    rclone_config: "ENCRYPTED[3a193ee76fd13e3e3ef69ee000f0f7b8e55e753707fe469e312248fc4464cfd7b443a0c8480029c3accf1c63b64a38a2]"

task:
    name: cirrus-ci
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

    memantau_background_script:
      - bash memantau
    mengunduh_ccache_background_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - df -h && free -h && nproc && cat /etc/os* && env
      - cd /tmp
      - time aria2c https://drive.fourninesix.workers.dev/0:/ccache/ccache.tar.gz -x16 -s50
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
    mengsinkronisasi_script:
      - ./sinkronisasi
    membuat_akhir_script:
      - bash membuat_akhir
    mengunggah_script:
      - ./mengunggah
