#!/bin/bash
cd /tmp/rom
source build/envsetup.sh
lunch havoc_merlin-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export TZ=UTC

ccache -M 50G
ccache -o compression=true
ccache -z

make_rom(){
    brunch havoc_merlin-userdebug
	zip=$(up out/target/product/merlin/*zip)
	echo " "
	echo "$zip"
}

up(){
        curl --upload-file $1 https://transfer.sh/ 
}

make_rom
