#!/bin/bash

sudo apt install wget
sudo apt install python2 -y
git config --global  user.name "l3773"
git config --global  user.email "l3773683@gmail.com"
cd /tmp/rom

repo init -q --no-repo-verify --depth=1 https://github.com/hentaiOS/platform_manifest -b Rika -g default,-device,-mips,-darwin,-notdefault
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# clone tree
git clone https://github.com/linear21/common -b eleven device/xiaomi/mt6768-common --depth=1
git clone https://github.com/linear21/android_device_xiaomi_merlin -b hentai device/xiaomi/merlin --depth=1
git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_merlin -b eleven vendor/xiaomi/merlin  --depth=1
git clone https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768 -b eleven kernel/xiaomi/mt6768 --depth=1
git clone https://github.com/PixelExperience/device_mediatek_sepolicy_vndr -b eleven device/mediatek/sepolicy_vndr --depth=1
git clone https://github.com/PixelExperience/vendor_mediatek_interfaces -b eleven vendor/mediatek/interfaces

# apply patch
cd frameworks/base &&  wget https://github.com/PixelExperience/frameworks_base/commit/37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch && git apply 37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch
cd -
cd frameworks/opt/net/ims &&  wget https://github.com/PixelExperience/frameworks_opt_net_ims/commit/661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch && git apply 661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch
cd -
cd frameworks/opt/net/wifi &&  wget https://github.com/PixelExperience/frameworks_opt_net_wifi/commit/3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch && git apply 3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch
cd - 

rm -rf build/make
git clone https://github.com/linear21/platform_build build/make
rm -rf vendor/hentai
git clone https://github.com/TeraaBytee/vendor_hentais